"""add auth_provider column

Revision ID: eb9ea848b9d4
Revises: a03281c166bf
Create Date: 2026-06-30 07:47:37.897989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb9ea848b9d4'
down_revision: Union[str, Sequence[str], None] = 'a03281c166bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_provider', sa.String(length=20), server_default='local', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth_provider')
    # ### end Alembic commands ###
